carnival/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^admin/', admin.site.urls),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^espanol/$', views.espanol, name='espanol'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^dayof/$', views.dayof, name='dayof')
]

core/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    picture = models.ImageField(upload_to='', blank=True)
    pics=[]

core/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('picture', )
        widgets = {
            'picture': forms.ClearableFileInput(attrs={'multiple': True,'style': 'display: none;'})
        }

core/views.py
from django.core.files.storage import default_storage
from django.shortcuts import render
from googleapiclient.http import MediaFileUpload
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

from carnival import settings
from .forms import ImageForm
from .models import Image

def index(request):
    context = {
        'navbar': 'home'
    }
    return render(request, 'core/index.html', context)


def about(request):
    context = {
        'navbar': 'about'
    }
    return render(request, 'core/about.html', context)


def espanol(request):
    context = {
        'navbar': 'espanol'
    }
    return render(request, 'core/espanol.html', context)


def contact(request):
    return


def dayof(request):
    success=False
    if request.method == 'POST':
        form = ImageForm(request.POST,request.FILES)
        #if form.is_valid():
        #image = Image()
        files = request.FILES.getlist('picture')
        #image.picture = form.cleaned_data["picture"]
        #image.save()
        creds = None
        SCOPES = ['https://www.googleapis.com/auth/drive']
        if os.path.exists('token.pickle'):
            with open('token.pickle', 'rb') as token:
                creds = pickle.load(token)
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
                creds = flow.run_local_server()
            with open('token.pickle', 'wb') as token:
                pickle.dump(creds, token)
        service = build('drive', 'v3', credentials=creds)
        folder_id = '1dOy-chl03stjflrlu4jl6nxyWhvAZNmR'
        for f in files:
            #print(f)
            #image.pics.append(f)
            save_path = os.path.join(settings.MEDIA_ROOT, str(f))
            default_storage.save(str(f), f)
            file_metadata = {'name': str(f),'parents': [folder_id]}
            media = MediaFileUpload(save_path,mimetype='image/jpeg')
            service.files().create(body=file_metadata,media_body=media,fields='id').execute()
            default_storage.delete(str(f))
        #image.delete()
        success=True

    else:
        form = ImageForm()

    return render(request, "core/dayof.html", {'form': form, 'navbar': '', 'success': success, 'nobanner': True})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MBHS Carnival of Animals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script defer src="https://www.googletagmanager.com/gtag/js?id=UA-129370353-2"></script>
    <script defer>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'UA-129370353-2');</script>
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

templates/core/base.html
{% extends "base.html" %}
{% block head %}
    {% load static %}
    <link rel='stylesheet' href="{% static 'core/css/bootstrap.min.css' %}" type="text/css">
    <script src="{% static 'core/js/jquery-3.2.1.min.js' %}"></script>
    <script defer src="{% static 'core/js/popper.js' %}"></script>
    <script defer src="{% static 'core/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/custom.css' %}">
    <link href="{% static 'core/css/aos.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'note.ico' %}"/>
{% endblock %}
{% block body %}
    {% if not nobanner %}
    <a href="{% url 'dayof' %}" class="d-block p-3 text-center text-white bg-primary b4b">Click to upload pictures from the event!</a>
    {% endif %}
    <nav class="navbar navbar-expand-md navbar-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button> <!-- /.navbar-toggler -->
        <div class="collapse navbar-collapse">
            <div class="mx-auto">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link {% if navbar == 'home' %} active {% endif %}" href="{% url 'index' %}">Home</a></li> <!--Use {% ifequal request.path 'URLPATH'%} active {% endifequal%} for Django -->
                    <li class="nav-item"><a class="nav-link" href="ticket-modal" data-toggle="modal" data-target="#ticket-modal">Tickets</a></li>
                    <li class="nav-item"><a class="nav-link {% if navbar == 'about' %} active {% endif %}" href="{% url 'about' %}">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="contact-modal" data-toggle="modal" data-target="#contact-modal">Contact</a></li>
                    <li class="nav-item espanol"><a class="nav-link" href="{% url 'espanol' %}">Español</a></li>
                </ul>
            </div>
        </div> <!-- /.navbar-collapse -->
    </nav>
    {% include 'core/includes/base-ticket-modal.html' %}
    {% include 'core/includes/base-contact-modal.html' %}
    {% block content %}
    {% endblock %}
    <script>$(function(){$("a[href*='#']").on('click',function(e){e.preventDefault();$('html,body').animate({scrollTop:$($(this).attr('href')).offset().top-50},1000);});});</script>
    <script src="{% static 'core/js/aos.js' %}"></script>
    <script>AOS.init({duration:1000,offset:0,})</script>
{% endblock %}

templates/core/dayof.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container" id="dayof">
    {% if success %} <div class="alert alert-success" role="alert">Success!</div> {% endif %}
        <div class="row">
            <div class="col-md">
                <h1 class="dayof-cards-title my-4 text-center">Thanks for Coming!</h1>
                <div class="card">
                    <div class="card-header">
                        <h1 class="card-title">Submit Photos</h1>
                    </div>
                    <div class="card-body">
                        <p>Click "Upload Pictures," select as many pictures as you want, then click "Submit."</p>
                        <form enctype="multipart/form-data" action="{% url 'dayof' %}" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <label for="id_picture" class="btn">
                                Upload Pictures
                            </label>
                            <p>By clicking "Submit," I give permission to Montgomery Blair Instrumental Music to use the submitted photos in promotional materials.</p>
                            <input type="submit" value="Submit" class="btn ">
                        </form>
                    </div>
                </div>
            </div>
            <!--<div class="col-md">
                <div class="card h-100">
                    <div class="card-header">
                        <h1 class="card-title">Map</h1>
                    </div>
                    <div class="card-body">
                        <a href="{% static 'core/img/background/map.png' %}" target="_blank" class="btn">Click for the event map</a>
                    </div>
                </div>
            </div>-->
        </div>
    </div>
{% endblock %}

templates/core/espanol.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
    <script>
        AOS.init({
            duration: 1200,
        })
    </script>
    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "http://carnival.mbhs.edu/"
      },{
        "@type": "ListItem",
        "position": 2,
        "name": "Español",
        "item": "http://carnival.mbhs.edu/espanol/"
      }]
    }
    </script>
    <style>
        .card-header {
            background-color: #A52814;
            color: white;
        }
        .card-body {
            background-color: rgb(20,20,47);
            color:white;
        }
        .btn {
            font-family: 'Luckiest Guy', sans-serif;
            font-size: 1.5em;
        }
        .btn:hover {
            color:black;
        }
    </style>
    <div id="espanol-page">
        <div class="container">
            <div class="row" style="margin-top: 4em;">
                <div class="col-sm-12"><div class="card">
                    <div class="card-header">
                        Español
                    </div>
                    <div class="card-body">
                        <!--<p class="card-text">Esta página se actualizará en enero. Véase más adelante el volante del año pasado.</p>
                        <p class="card-text">Habrá voluntarios y estudiantes que hablan español gustosos de ayudarles a disfrutar de este divertido Festival</p>
                        <p class="card-text">¡No se lo pierda!</p>
                        <a class="btn btn-block btn-large btn-outline-light mx-auto py-4 mb-4" target="_blank" href="https://blairmusic.ticketleap.com/carnival/" role="button">Entradas
                            <span class="text-muted d-block">efectivo solo en la puerta</span>
                        </a>-->
                        <div class="embed-responsive embed-responsive-210by297">
                            <embed class="embed-responsive-item" src="{% static 'espanol2019.pdf' %}">
                            </embed>
                        </div>
                        <!--<a class="btn btn-block btn-large btn-outline-light mx-auto py-4 mt-4" target="_blank" href="https://blairmusic.ticketleap.com/carnival/" role="button">Entradas
                            <span class="text-muted d-block">efectivo solo en la puerta</span>
                        </a>-->
                    </div>
                </div></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/core/includes/about-carousel.html
{% load static %}
<div id="photo-carousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#photo-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#photo-carousel" data-slide-to="1"></li>
        <li data-target="#photo-carousel" data-slide-to="2"></li>
        <li data-target="#photo-carousel" data-slide-to="3"></li>
        <li data-target="#photo-carousel" data-slide-to="4"></li>
        <li data-target="#photo-carousel" data-slide-to="5"></li>
    </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'core/img/background/orchestra.jpg' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'core/img/background/amanuel.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'core/img/background/buzzing.jpeg' %}" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'core/img/background/casper.jpg' %}" alt="Fourth slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'core/img/background/eden.jpg' %}" alt="Fifth slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'core/img/background/will.jpg' %}" alt="Sixth slide">
    </div>
  </div>
  <!--<div class="carousel-caption d-none d-md-block text-center">
      <h3 class="display-3">About the Carnival</h3>

  </div>-->
  <a class="carousel-control-prev" data-target="#photo-carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" data-target="#photo-carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

templates/core/includes/base-contact-modal.html
{% load static %}
<div class="modal fade contact-modal" tabindex="-1" role="dialog" aria-labelledby="contact-modal" aria-hidden="true" id="contact-modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
              <h2 class="modal-title mx-auto d-block">Contact Us</h2>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <div class="container-fluid">
                  <div class="row">
                      <div class="col-sm-5">
                          <div class="row h-50 hello-row">
                              <h1 class="display-4 d-block mx-auto">Hello!</h1>
                              <div class="icon-div d-block mx-auto">
                                  <a href="https://twitter.com/mbhsmusic" target="_blank"><i class="fa fa-lg fa-twitter"></i></a>
                                  <a href="https://www.facebook.com/mbhsmusic" target="_blank"><i class="fa fa-lg fa-facebook"></i></a>
                                  <a href="https://www.instagram.com/mbhsmusicdept/" target="_blank"><i class="fa fa-lg fa-instagram"></i></a>
                                  <a href="https://www.youtube.com/channel/UC0oe0pAXu9eMP9XLls1K4rw" target="_blank"><i class="fa fa-lg fa-youtube"></i></a>
                              </div>
                          </div>
                          <div class="row h-50 address-row align-text-bottom">
                              <p class="lead text-center">
                                  51 University Blvd E, Silver Spring, MD 20901
                              </p>
                          </div>
                      </div>
                      <div class="col-sm-7">
                          <form action="" class="form">
                              <label class="d-block" for="fname">First Name</label>
                              <input class="w-100 form-control" type="text" id="fname" name="firstname" placeholder="">

                              <label class="d-block" for="lname">Last Name</label>
                              <input class="w-100 form-control" type="text" id="lname" name="lastname" placeholder="">

                              <label class="d-block" for="email">Email</label>
                              <input class="w-100 form-control" type="text" id="name" name="email" placeholder="">

                              <label class="d-block" for="subject">Message</label>
                              <textarea class="w-100 form-control" id="subject" name="subject" placeholder="Comments/Questions" style="height:200px"></textarea>

                              <button class="btn btn-outline-dark w-100 mt-3" type="submit">Send</button>
                            </form>
                      </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
</div>
<script>
$(document.body).on('shown.bs.modal,show.bs.modal', function () {
    $('body').css('padding-right','0');
});
</script>

templates/core/includes/base-ticket-modal.html
{% load static %}
<div class="modal fade ticket-modal" tabindex="-1" role="dialog" aria-labelledby="ticket-modal" aria-hidden="true" id="ticket-modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
              <img class="d-block" src="{% static 'core/img/icon/ticket.svg' %}" alt="ticket.svg" style="width:5em;height:2.5em;position:absolute;">
              <h2 class="modal-title mx-auto d-block">Tickets</h2>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <p class="lead text-center enlarge">
                 Online ticket sales are over but you can buy tickets at the door!
              </p>
              <!--<p class="lead text-center enlarge">
                 $5 ticket sales closed
              </p>
              <p class="lead text-center enlarge">
                  Discounted tickets ($7) on sale until March 6th
              </p>
              <a class="btn btn-block btn-large btn-outline-light mx-auto py-4" target="_blank" href="https://blairmusic.ticketleap.com/2019carnival/" role="button">Buy Tickets Now!</a>-->
              <p class="my-3">
                  Tickets at the door (cash preferred):
              </p>
              <ul>
                  <li>1 for $10</li>
                  <li>2 for $18</li>
                  <li>3 for $25</li>
                  <li>4 for $30</li>
                  <li>5 for $35</li>
                  <li>$5 for each additional over 5</li>
              </ul>
          </div>
        </div>
      </div>
</div>
<script>
$(document.body).on('shown.bs.modal,show.bs.modal', function () {
    $('body').css('padding-right','0');
});
</script>
<!-- <a href="https://blairmusic.ticketleap.com/carnival/" role="button" class="btn btn-outline-dark d-block">Presale Tickets $5</a> -->

templates/core/includes/index-about-section.html
{% load static %}
<section id="about-container">
    <div class="top-separator">
        <a href="#about-container"><div class="arrow"></div></a>
        <svg width="192" height="61" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 160.7 61.5" enable-background="new 0 0 160.7 61.5" xml:space="preserve"><path fill="#9fd2ff" d="M80.3,61.5c0,0,22.1-2.7,43.1-5.4s41-5.4,36.6-5.4c-21.7,0-34.1-12.7-44.9-25.4S95.3,0,80.3,0c-15,0-24.1,12.7-34.9,25.4S22.3,50.8,0.6,50.8c-4.3,0-6.5,0,3.5,1.3S36.2,56.1,80.3,61.5z"></path></svg>
    </div>
    <main role="main" class="about">
        <img class="trumpet-svg" data-aos="fade-up" src="{% static 'core/img/icon/piano.svg' %}" alt="Piano">
        <img class="violin-svg" data-aos="fade-up" src="{% static 'core/img/icon/carnivalxylo.png' %}" alt="Xylophone">
        <img class="sax-svg" data-aos="fade-up" src="{% static 'core/img/icon/clarinet.svg' %}" alt="Flute">

        <!-- <h1 class="about-lead">About /</h1> !-->
        <div>
            <h1 class="about-title">The Event</h1>
            <p class="">
                The Carnival of the Animals is a community music festival hosted by Montgomery Blair High School.
                Our goal is to provide a fun and educational musical experience for young children.
            </p>
            <p class="">
                The festival's main event will be a performance of <i>Carnival of the Animals</i>, by Camille Saint-Saëns.
                We will also feature an "Instrument Petting Zoo," a marching band, instrument making, face painting,
                raffle prizes, and more.
            </p>
        </div>
        <div>
            <h1 class="about-title">Instrument Petting Zoo</h1>
            <p class="">
                Member of Blair Bands and Orchestras will be on hand with their instruments
                so kids can see them, learn a bit about them and can try them out. We expect
                to have a full compliment of band and orchestra instruments,
                as well as pianos on hand.  This is something the National Symphony Orchestra
                does, but it costs way more and is all the way downtown!
            </p>
        </div>
        <div>
            <h1 class="about-title">Raffle Prizes</h1>
            <p class="">
                <!--Win a FREE week of summer camp @ <a href="#">Roundhouse Theatre</a>, a ukulele, free music
                lessons, and more!-->
                You could win books, t-shirts, music lessons, and more, including a cello and free week of summer camp!
            </p>
            <div style="width:100%">
                <a href="{% url 'about' %}" role="button" class="btn btn-outline-dark mb-2" style="width:100%">Learn More!</a>
            </div>
        </div>
    </main>
    <!--<a href="#schedule-container"><span class="section-btn"></span></a>-->
</section>

templates/core/includes/index-map-section.html
<div id="map-container">
    <div id="map"></div>
    <script>function initMap(){var mbhs={lat:39.0183042,lng:-77.0138447};var map=new google.maps.Map(document.getElementById('map'),{zoom:15,center:mbhs});var marker=new google.maps.Marker({position:mbhs,map:map});}</script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZtlqCbWxCZWGU0Ii5gT__EdQaYNRa5ic&callback=initMap"></script>
</div>

templates/core/includes/index-schedule-section.html
{% load static %}
<section id="schedule-container">
    <main role="main" class="schedule">

        <h1 class="schedule-title">Schedule</h1>
        <p class="desc">
            Our event will run 1 pm – 4 pm. The format is
            designed to accommodate families whenever you arrive. We will run the
            instrument petting zoo the entire time, and both the Orchestra and
            the Marching Band will perform twice, both times for kid-friendly durations
            (25 minutes, and 15 minutes respectively). You can go to one or both
            performances.
            See the schedule below.
        </p>
        <div class="row">
            <div class="col-sm-4">
                <h1 class="time-header">1:00 PM</h1>
            </div>
            <div class="col-sm-8">
                <p class="time-description">
                    Festival opens. Ongoing Festivities: Instrument Petting Zoo, Face Painting, Bake Sale, etc.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <h1 class="time-header">1:15 PM</h1>
            </div>
            <div class="col-sm-8">
                <p class="time-description">
                    Marching Band Performance (15 min) <br> Raffle Drawing 1
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <h1 class="time-header">1:45 PM</h1>
            </div>
            <div class="col-sm-8">
                <p class="time-description">
                    Carnival of the Animals Performance 1
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <h1 class="time-header">2:30 PM</h1>
            </div>
            <div class="col-sm-8">
                <p class="time-description">
                    Marching Band Performance (15 min) <br> Raffle Drawing 2
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <h1 class="time-header">3:00 PM</h1>
            </div>
            <div class="col-sm-8">
                <p class="time-description">
                    Carnival of the Animals Perfomance 2
                </p>
            </div>
        </div>
        <div class="row">   
            <div class="col-sm-4">
                <h1 class="time-header">3:45 PM</h1>
            </div>
            <div class="col-sm-8">
                <p class="time-description">
                    Instrument petting zoo closes
                </p>
            </div>
        </div>
        <div class="row">   
            <div class="col-sm-4">
                <h1 class="time-header">4:00 PM</h1>
            </div>
            <div class="col-sm-8">
                <p class="time-description" id="closing">
                    Closing
                </p>
            </div>
        </div>
    </main>
    <!--<a href="#sponsors-container"><span class="section-btn"></span></a>-->
</section>

templates/core/includes/index-sponsors-section.html
{% load static %}
<div id="sponsors-container">
    <main class="sponsors" role="main">
        <h1 class="sponsors-title">Thanks to Our Wonderful Sponsors</h1>
        <div class="content mx-auto">
            <div class="row text-center mx-auto">
                <!--<div class="col-2-md text-center">
                    <a href="https://hmtrad.com/" target="_blank">
                        <img class="img-fluid" src="{% static 'core/img/background/house-musical-traditions.png' %}" alt="alt">
                    </a>
                    <p style="font-size: .75em;">House of Musical Traditions</p>

                </div>-->
                <div class="col text-center">
                    <a href="https://www.roundhousetheatre.org/" target="_blank">
                        <img class="img-fluid" src="{% static 'core/img/background/round-house-theatre.png' %}" alt="alt">
                    </a>
                </div>
                <div class="col text-center">
                    <a href="http://jordankitts.com/" target="_blank">
                        <img class="img-fluid" src="{% static 'core/img/background/jordan-kitts.png' %}" alt="alt">
                    </a>
                </div>
                <div class="col text-center">
                    <a href="http://www.ismw.org/" target="_blank">
                        <img class="img-fluid" src="{% static 'core/img/background/intl-school-music.png' %}" alt="alt">
                    </a>
                </div>
                <div class="col text-center">
                    <a href="https://www.thehighwoodtheatre.org/" target="_blank">
                        <img class="img-fluid" src="{% static 'core/img/background/housewood-theatre.png' %}" alt="alt">
                    </a>
                </div>
                <div class="col text-center">
                    <a href="https://www.musicarts.com/" target="_blank">
                        <img class="img-fluid" src="{% static 'core/img/background/musicandarts.png' %}" alt="alt">
                    </a>
                </div>
            </div>
        </div>
        <p>Thanks also to the MCPS Educational Foundation for their support.</p>
    </main>
    <!--<a href="#map-container"><span class="section-btn"></span></a>-->
</div>

templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<script type="application/ld+json">{"@context": "http://schema.org","@type": "BreadcrumbList","itemListElement": [{"@type": "ListItem","position": 1,"name": "Home","item": "http://carnival.mbhs.edu/"}]}</script>
<section id="cover-container">
    <div class="row">
        <div class="d-none d-lg-inline col">
            <img src="/static/core/img/icon/cello-color.svg" class="d-none d-lg-inline w-75 mx-2 my-2" alt="Cello">
        </div>
        <div role="main" class="cover col col-lg-6">
            <h1 class="cover-lead" >MBHS Music Presents:</h1>
            <span class="badge badge-pill badge-light" style="font-size: 1.5em; color: #fff; background-color: #1e88e5;">The 2<sup>nd</sup> Annual</span>
            <h1 class="cover-title mt-3" >Carnival of the Animals</h1>
            <!-- <object style="fill:white" data="{% static 'core/img/background/cello-outline-bottom.svg' %}" type="image/svg+xml"></object> -->
            <p class="lead mb-0">
                Saturday, March 9 | 1PM - 4PM
            </p>
            <p class="lead">
                <a href="https://www.google.com/maps/place/Montgomery+Blair+High+School/@39.0187326,-77.0139629,17z/data=!4m19!1m13!4m12!1m4!2m2!1d-77.0119759!2d39.0182537!4e1!1m6!1m2!1s0x89b7cf586f9b73d5:0xc227c473fffb50c7!2sMontgomery+Blair+High+School,+51+University+Blvd+E,+Silver+Spring,+MD+20901!2m2!1d-77.011656!2d39.0183042!3m4!1s0x89b7cf586f9b73d5:0xc227c473fffb50c7!8m2!3d39.0183042!4d-77.011656" target="_blank">
                    51 University Blvd E, Silver Spring, MD 20901
                </a>
            </p>
            <div id="testimonials" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <p>"My son is 3 years old, and he really enjoys music. It was wonderful to watch his curiosity come alive at Carnival of the Animals."
                </p>
                </div>
                <div class="carousel-item">
                    <p>"The students were delightful and the event was a huge success. $5 was a bargain!"
                </p>
                </div>
                <div class="carousel-item">
                  <p>"The reed he got to keep is in his box of prized treasures!"
                </p>
                </div>
                <div class="carousel-item">
                  <p>"I was particularly impressed with the students as they encouraged the children to play and handle their instruments."
                </p>
                </div>
                <div class="carousel-item">
                  <p>"This was truly an amazing event that should become a tradition!"
                </p>
                </div>
                <div class="carousel-item">
                  <p>"I can’t believe this was your first time. It was really terrific."
                </p>
                </div>
                <div class="carousel-item">
                  <p>"We loved the event and we will recommend it to all our neighbors next year!"
                      </p>
                </div>
              </div>
            </div>
            <!--<a target="_blank" href="https://blairmusic.ticketleap.com/2019carnival/" role="button" class="btn btn-solid d-block">Presale Tickets</a>-->
            <a href="#sponsors-container" role="button" class="btn btn-outline-light d-block">Check out our Sponsors!</a>
        </div>
        <div class="d-none d-lg-inline col">
            <img src="/static/core/img/icon/violin.png" class="d-none d-lg-inline w-100 my-2" alt="Lion">
        </div>
    </div>
    <!--<a href="#about-container"><span class="section-btn"></span></a>-->
</section>
{% include 'core/includes/index-about-section.html' %}
{% include 'core/includes/index-schedule-section.html' %}
{% include 'core/includes/index-sponsors-section.html' %}
{% include 'core/includes/index-map-section.html' %}
<!--sponsors : Thanks to our sponsors: Highwood Theatre, House of Musical Traditions,
International School of Music, Jordan Kitt’s Music, Roundhouse Theatre, and to the MCPS
Foundation and the Neighborhood Event Matching Grant Program for their support !-->
<!-- MAPS !-->
{% endblock %}